apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-team2
  namespace: team2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-team2
  template:
    metadata:
      labels:
        app: myapp-team2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-team2-service
  namespace: team2
spec:
  selector:
    app: myapp-team2
  ports:
    - port: 80
      targetPort: 80
